// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "9113bae9-f8e9-4f62-9ada-e159641b2d69";

const char SSID[]               = "My_SSID";    // Network SSID (name)
const char PASS[]               = "INTERNET1";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "AMMBVKL7GCK44OIZ02SB";    // Secret device password

void onBillAChange();
void onBillBChange();
void onBillCChange();
void onBillDChange();
void onLastConChange();

String bill_A;
String bill_B;
String bill_C;
String bill_D;
int last_con;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bill_A, READWRITE, ON_CHANGE, onBillAChange);
  ArduinoCloud.addProperty(bill_B, READWRITE, ON_CHANGE, onBillBChange);
  ArduinoCloud.addProperty(bill_C, READWRITE, ON_CHANGE, onBillCChange);
  ArduinoCloud.addProperty(bill_D, READWRITE, ON_CHANGE, onBillDChange);
  ArduinoCloud.addProperty(last_con, READWRITE, ON_CHANGE, onLastConChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
